name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pylama:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install poetry==1.4.0
      - run: poetry install
      - run: poetry run pylama
        env:
          FORCE_COLOR: 1
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - run: python -m pip install poetry
      - run: poetry install -vvvv
      - run: poetry run mypy
        env:
          FORCE_COLOR: 1

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'

    services:
      rabbitmq:
        image: docker://rabbitmq
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v2
      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - run: python -m pip install poetry
      - run: poetry install -vvvv
      - run: >-
          poetry run pytest \
            -vv \
            --cov=patio_rabbitmq \
            --cov-report=term-missing \
            --doctest-modules \
            --aiomisc-test-timeout=30 \
            tests
        env:
          FORCE_COLOR: 1
# TODO: Uncomment after open this sources
#      - run: poetry run coveralls
#        env:
#          COVERALLS_PARALLEL: 'true'
#          COVERALLS_SERVICE_NAME: github
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  finish:
#    needs:
#       - tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Coveralls Finished
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.github_token }}
#          parallel-finished: true
